matrix:
  include:
    - stage: test
      name: test_linux_2_7
      os: linux
      language: python
      env: MINICONDA="https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh" PYTHONVER="2.7"
      install:
        - export PATH="$HOME/miniconda/bin:$PATH"
        - wget ${MINICONDA} -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - conda info -a
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda install -y -c conda-forge python=${PYTHONVER} coverage pandas scandir h5io numpy pysqa tqdm
        - pip install --pre .
      script:
        - coverage run -m unittest discover tests

    - name: test_linux_3_7
      os: linux
      language: python
      env: MINICONDA="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" PYTHONVER="3.7"
      install:
        - export PATH="$HOME/miniconda/bin:$PATH"
        - wget ${MINICONDA} -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - conda info -a
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda install -y -c conda-forge python=${PYTHONVER} coveralls coverage pandas scandir h5io numpy pysqa tqdm
        - pip install --pre .
      script:
        - coverage run -m unittest discover tests
      after_success:
        - coveralls
        - coverage xml
        - pip install codacy-coverage
        - python-codacy-coverage -r coverage.xml
      deploy:
        - provider: pypi
          user: jan-janssen
          password: ${PYPI_UPLOAD_TOKEN}
          allow_failure: true
          on:
            branch: master
        - provider: pypi
          user: jan-janssen
          password: ${PYPI_UPLOAD_TOKEN}
          allow_failure: true
          on:
            tags: true

    - name: test_osx_2_7
      os: osx
      language: generic
      env: MINICONDA="https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh" PYTHONVER="2.7"
      install:
        - export PATH="$HOME/miniconda/bin:$PATH"
        - wget ${MINICONDA} -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - conda info -a
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda install -y -c conda-forge python=${PYTHONVER} coverage pandas scandir h5io numpy pysqa tqdm
        - pip install --pre .
      script:
        - coverage run -m unittest discover tests

    - name: test_osx_3_7
      os: osx
      language: generic
      env: MINICONDA="https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh" PYTHONVER="3.7"
      install:
        - export PATH="$HOME/miniconda/bin:$PATH"
        - wget ${MINICONDA} -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - conda info -a
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda install -y -c conda-forge python=${PYTHONVER} coverage pandas scandir h5io numpy pysqa tqdm
        - pip install --pre .
      script:
        - coverage run -m unittest discover tests
