name: Python package

on: [push]

jobs:
  run: 
    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 4
      matrix:
        operating-system: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Download Miniconda
      run: wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - name: Install Miniconda
      run: bash miniconda.sh -b -p /home/runner/work/miniconda
    - name: Configure Miniconda
      run: export PATH="/home/runner/work/miniconda/bin:$PATH"
    - name: Update conda
      run: conda update -q conda
    - name: Install Dependences
      run: conda create -n scisweeper -q --yes -c conda-forge coverage pandas scandir h5io numpy pysqa tqdm pip
    - name: Install package 
      run: |
        source /home/runner/work/miniconda/bin/activate scisweeper
        pip install --pre .
    - name: Test with coverage
      run: |
        source /home/runner/work/miniconda/bin/activate scisweeper
        coverage run -m unittest discover tests
